swagger: "2.0"
info:
  description: "Project for testing, e2e, unit tests and integration tests"
  version: "1.0.0"
  title: "Project Test"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/v2"
tags:
- name: "todo"
  description: "A todo project"
  externalDocs:
    description: "Find out more on Github"
    url: "https://github.com/JeremDlcn/ynov-nantes-unit-tests"
schemes:
  - "https"
  - "http"
paths:
  /todo:
    get:
        tags:
          - todo
        description: "See the list of all todos"
        responses:
          200:
            description: Success
            schema:
              type: array
              items:
                $ref: "#/definitions/Todo"
          400:
            description: Bad request
            schema:
              $ref: "#/definitions/Error"
    post:
        tags:
          - todo
        description: "Create a new todo item"
        parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: object
            properties:
              text:
                type: string
              done:
                type: boolean
        responses:
          201:
            description: Success
            schema:
              $ref: "#/definitions/Todo"
          400:
            description: Bad request
            schema:
              $ref: "#/definitions/Error"
  /todo/{id}:
    patch:
        tags:
          - todo
        description: "Update a specific todo item"
        operationId: "id"
        parameters:
        - in: "path"
          name: "id"
          required: true
          type: "integer"
        responses:
          200:
            description: Success
            schema:
              $ref: "#/definitions/Todo"
          400:
            description: Bad request
            schema:
              $ref: "#/definitions/Error"

definitions:
  Todo:
    type: "object"
    properties:
      done:
        type: boolean
      _id:
        type: string
      text:
        type: string
      _v:
        type: number

  Error:
    type: "object"
    properties:
      message:
        type: "string"
      _message:
        type: "string"
      name:
        type: "string"
      errors:
        type: "array"
        items:  
          type: "object"
          properties:
            message:
              type: "string"
            name:
              type: "string"
            path:
              type: "string"
            kind:
              type: "string"
            properties:
              type: "object"
              properties:
                message:
                  type: "string"
                type:
                  type: "string"
                path:
                  type: "string"